name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run installing nodejs and npm
      run: apt install -y nodejs
    - name: Show version of the nodejs
      run: node --version
